blank_issues_enabled: true
contact_links:
  - name: Question or Discussion
    url: https://github.com/dvdred/antipattern-bird/discussions
    about: Ask questions or discuss ideas with the community
  - name: Email Contact
    url: mailto:dvdred@gmail.com
    about: Contact the maintainer directly
