name: Build and Release
permissions:
  contents: write
on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
jobs:
  test-files-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - run: pip install -r requirements.txt
      - run: python unit-tests.py

  test-files-linux:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - run: pip install -r requirements.txt
      - run: python unit-tests.py

  build-windows:
    needs: test-files-windows
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - run: pip install pyinstaller pillow
      - run: pip install -r requirements.txt
      - run: python -c "from PIL import Image; img = Image.open('icon32.png'); img.save('icon.ico', format='ICO')"
      - run: >
          pyinstaller --onefile --noconsole
          --add-data "icon32.png;."
          --add-data "*.wav;."
          --add-data "*ttf;."
          --icon "icon.ico"
          --name antipattern-bird app.py
      - uses: actions/upload-artifact@v4
        with:
          name: antipattern-bird-win-x64
          path: dist/antipattern-bird.exe
      - uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: dist/antipattern-bird.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  build-linux:
    needs: test-files-linux
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - run: pip install pyinstaller
      - run: pip install -r requirements.txt
      - run: >
          pyinstaller --onefile
            --strip
            --exclude-module pytest
            --exclude-module setuptools
            --exclude-module tkinter
            --add-data "icon32.png:."
            --add-data "*.wav:."
            --add-data "*.ttf:."
            --name antipattern-bird app.py
      # Opzionale: compressione UPX (può ridurre ulteriormente)
      - run: |
          sudo apt-get update
          sudo apt-get install -y upx
          upx --best --lzma dist/antipattern-bird
        continue-on-error: true
      - uses: actions/upload-artifact@v4
        with:
          name: antipattern-bird-linux-x64
          path: dist/antipattern-bird
      - uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: dist/antipattern-bird
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}